[package]
name = "rsa"
version = "0.1.0"
edition = "2021"
license = "MIT"
license-file = "LICENSE"

[dependencies]
rand = "0.8.5"
num-bigint = { version =  "0.4.6", features = ["rand"] }
num-traits = "0.2.19"
